### ISSUE TITLE
mj-meo-dmt should be listed in the entry page

### ISSUE THREAD

**Issue by lordmauve** [grimfang/pyweek21#1]
Don't know if you saw [my message on the site](https://www.pyweek.org/d/5977/).

mj-meo-dmt should be listed in the team on the [entry page](https://www.pyweek.org/e/Little_Drop/), as he has made significant contributions to your project, so that you can be included in the team competition rather than the solo competition.

**Comment by fireclawthefox** [comment]
Hello lordmauve,
mj-meo-dmt removed himself from the list as it didn't feel right for him to get credited for the few additions he made. If it's a problem that our entry is now a solo entry, I'll talk to him about re-adding him to the entry.

**Comment by lordmauve** [comment]
Ok. Just according to [the contributors page](https://github.com/grimfang/pyweek21/graphs/contributors) he contributed a thousand lines or so. Your call.
